name: unit-tests
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  unit-test:
    name: Unittesting on ${{ matrix.os }} with python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos, ubuntu, windows]
        python-version: ["3.12"]
        include:
          - os: ubuntu
            python-version: "3.10"
          - os: ubuntu
            python-version: "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Conda and parcels
        uses: ./.github/actions/install-parcels
        with:
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
      - name: Unit test
        run: |
          coverage run -m pytest -v -s --html=${{ matrix.os }}_${{ matrix.python-version }}_unit_test_report.html --self-contained-html tests
          coverage xml
      # - name: Codecov
      #   uses: codecov/codecov-action@v3.1.1
      #   with:
      #     flags: unit-tests
      # - name: Upload test results
      #   if: ${{ always() }} # Always run this step, even if tests fail
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     name: Unittest report
      #     path: ${{ matrix.os }}_${{ matrix.python-version }}_unit_test_report.html
